"""empty message

Revision ID: 9766e4c4ea5d
Revises: 
Create Date: 2024-03-20 22:37:47.271097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9766e4c4ea5d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ANNOUNCE", "MUSIC_LEAK", "VOCAL_LEAK", "CARD_LEAK", name="channelintentenum"
    ).create(op.get_bind())
    op.create_table(
        "channel_intent",
        sa.Column("guild", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.BigInteger(), nullable=False),
        sa.Column(
            "intent",
            postgresql.ENUM(
                "ANNOUNCE",
                "MUSIC_LEAK",
                "VOCAL_LEAK",
                "CARD_LEAK",
                name="channelintentenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("guild", "channel"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channel_intent")
    sa.Enum(
        "ANNOUNCE", "MUSIC_LEAK", "VOCAL_LEAK", "CARD_LEAK", name="channelintentenum"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
