# SPDX-FileCopyrightText: 2022-2023 Erik Chan <erikchan002@gmail.com>
# SPDX-FileCopyrightText: 2023-present TheerapakG <theerapakg@gmail.com>
#
# SPDX-License-Identifier: MIT

from datetime import datetime
from typing import List, Optional, Union

from pjsekai.enums import *
from pjsekai.models.master_data import *
from pjsekai.models.model import Model

class MusicDifficulty(Model):
    id: Optional[int]
    music_id: Optional[int]
    music_difficulty: Optional[Union[MusicDifficultyType, Unknown]]
    play_level: Optional[int]
    release_condition_id: Optional[int]
    total_note_count: Optional[int]

class MasterData(Model):
    game_characters: Optional[List[GameCharacter]]
    game_character_units: Optional[List[GameCharacterUnit]]
    outside_characters: Optional[List[OutsideCharacter]]
    character3ds: Optional[List[Character3d]]
    character2ds: Optional[List[Character2d]]
    character_profiles: Optional[List[CharacterProfile]]
    bonds: Optional[List[Bond]]
    bonds_live2ds: Optional[List[BondsLive2d]]
    bonds_rank_up_live2ds: Optional[List[BondsRankUpLive2d]]
    unit_profiles: Optional[List[UnitProfile]]
    action_sets: Optional[List[ActionSet]]
    areas: Optional[List[Area]]
    area_playlists: Optional[List[AreaPlaylist]]
    mob_characters: Optional[List[MobCharacter]]
    character_costumes: Optional[List[CharacterCostume]]
    card_costume3ds: Optional[List[CardCostume3d]]
    cards: Optional[List[Card]]
    skills: Optional[List[Skill]]
    card_episodes: Optional[List[CardEpisode]]
    card_rarities: Optional[List[CardRarity]]
    card_skill_costs: Optional[List[CardSkillCost]]
    musics: Optional[List[Music]]
    music_tags: Optional[List[MusicTag]]
    music_difficulties: Optional[List[MusicDifficulty]]
    music_vocals: Optional[List[MusicVocal]]
    music_dance_members: Optional[List[MusicDanceMember]]
    music_achievements: Optional[List[MusicAchievement]]
    music_video_characters: Optional[List[MusicVideoCharacter]]
    music_asset_variants: Optional[List[MusicAssetVariant]]
    music_collaborations: Optional[List[MusicCollaboration]]
    episode_music_video_costumes: Optional[List[EpisodeMusicVideoCostume]]
    release_conditions: Optional[List[ReleaseCondition]]
    play_level_scores: Optional[List[PlayLevelScore]]
    ingame_combos: Optional[List[IngameCombo]]
    ingame_notes: Optional[List[IngameNote]]
    ingame_note_judges: Optional[List[IngameNoteJudge]]
    ingame_play_levels: Optional[List[IngamePlayLevel]]
    ingame_cutins: Optional[List[IngameCutin]]
    ingame_cutin_characters: Optional[List[IngameCutinCharacter]]
    ingame_judge_frames: Optional[List[IngameJudgeFrame]]
    ingame_note_judge_technical_scores: Optional[List[IngameNoteJudgeTechnicalScore]]
    shops: Optional[List[Shop]]
    shop_items: Optional[List[ShopItem]]
    costume3d_shop_items: Optional[List[Costume3dShopItem]]
    area_items: Optional[List[AreaItem]]
    area_item_levels: Optional[List[AreaItemLevel]]
    materials: Optional[List[Material]]
    gachas: Optional[List[Gacha]]
    gacha_bonuses: Optional[List[GachaBonus]]
    gacha_bonus_points: Optional[List[GachaBonusPoint]]
    gacha_extras: Optional[List[GachaExtra]]
    gift_gacha_exchanges: Optional[List[GiftGachaExchange]]
    gacha_tabs: Optional[List[Union[dict, str, int]]]
    practice_tickets: Optional[List[PracticeTicket]]
    skill_practice_tickets: Optional[List[SkillPracticeTicket]]
    levels: Optional[List[Level]]
    unit_stories: Optional[List[UnitStory]]
    special_stories: Optional[List[SpecialStory]]
    configs: Optional[List[Config]]
    client_configs: Optional[List[ClientConfig]]
    wordings: Optional[List[Wording]]
    costume3ds: Optional[List[Costume3d]]
    costume3d_models: Optional[List[Costume3dModel]]
    costume3d_model_available_patterns: Optional[List[Costume3dModelAvailablePattern]]
    game_character_unit3d_motions: Optional[List[GameCharacterUnit3dMotion]]
    costume2ds: Optional[List[Costume2d]]
    costume2d_groups: Optional[List[Costume2dGroup]]
    topics: Optional[List[Topic]]
    live_stages: Optional[List[LiveStage]]
    stamps: Optional[List[Stamp]]
    multi_live_lobbies: Optional[List[MultiLiveLobby]]
    master_lessons: Optional[List[MasterLesson]]
    master_lesson_rewards: Optional[List[MasterLessonReward]]
    card_exchange_resources: Optional[List[CardExchangeResource]]
    material_exchanges: Optional[List[MaterialExchange]]
    material_exchange_summaries: Optional[List[MaterialExchangeSummary]]
    boost_items: Optional[List[BoostItem]]
    billing_products: Optional[List[BillingProduct]]
    billing_shop_items: Optional[List[BillingShopItem]]
    billing_shop_item_exchange_costs: Optional[List[BillingShopItemExchangeCost]]
    colorful_passes: Optional[List[ColorfulPass]]
    jewel_behaviors: Optional[List[JewelBehavior]]
    character_ranks: Optional[List[CharacterRank]]
    character_mission_v2s: Optional[List[CharacterMissionV2]]
    character_mission_v2_parameter_groups: Optional[List[CharacterMissionV2ParameterGroup]]
    character_mission_v2_area_items: Optional[List[CharacterMissionV2AreaItem]]
    system_live2ds: Optional[List[SystemLive2d]]
    normal_missions: Optional[List[NormalMission]]
    beginner_missions: Optional[List[BeginnerMission]]
    resource_boxes: Optional[List[ResourceBox]]
    live_mission_periods: Optional[List[LiveMissionPeriod]]
    live_missions: Optional[List[LiveMission]]
    live_mission_passes: Optional[List[LiveMissionPass]]
    penlight_colors: Optional[List[PenlightColor]]
    penlights: Optional[List[Penlight]]
    live_talks: Optional[List[LiveTalk]]
    tips: Optional[List[Tip]]
    gacha_ceil_items: Optional[List[GachaCeilItem]]
    gacha_ceil_exchange_summaries: Optional[List[GachaCeilExchangeSummary]]
    player_rank_rewards: Optional[List[PlayerRankReward]]
    gacha_tickets: Optional[List[GachaTicket]]
    honor_groups: Optional[List[HonorGroup]]
    honors: Optional[List[Honor]]
    honor_missions: Optional[List[HonorMission]]
    bonds_honors: Optional[List[BondsHonor]]
    bonds_honor_words: Optional[List[BondsHonorWord]]
    bonds_rewards: Optional[List[BondsReward]]
    challenge_lives: Optional[List[ChallengeLive]]
    challenge_live_decks: Optional[List[ChallengeLiveDeck]]
    challenge_live_stages: Optional[List[ChallengeLiveStage]]
    challenge_live_stage_exs: Optional[List[ChallengeLiveStageEx]]
    challenge_live_high_score_rewards: Optional[List[ChallengeLiveHighScoreReward]]
    challenge_live_characters: Optional[List[ChallengeLiveCharacter]]
    challenge_live_play_day_reward_periods: Optional[List[ChallengeLivePlayDayRewardPeriod]]
    virtual_lives: Optional[List[VirtualLive]]
    virtual_shops: Optional[List[VirtualShop]]
    virtual_items: Optional[List[VirtualItem]]
    virtual_live_cheer_messages: Optional[List[VirtualLiveCheerMessage]]
    virtual_live_cheer_message_display_limits: Optional[
        List[VirtualLiveCheerMessageDisplayLimit]
    ]
    virtual_live_tickets: Optional[List[VirtualLiveTicket]]
    virtual_live_pamphlets: Optional[List[VirtualLivePamphlet]]
    avatar_accessories: Optional[List[AvatarAccessory]]
    avatar_costumes: Optional[List[AvatarCostume]]
    avatar_motions: Optional[List[AvatarMotion]]
    avatar_skin_colors: Optional[List[AvatarSkinColor]]
    avatar_coordinates: Optional[List[AvatarCoordinate]]
    ng_words: Optional[List[NgWord]]
    rule_slides: Optional[List[RuleSlide]]
    facilities: Optional[List[Facility]]
    one_time_behaviors: Optional[List[OneTimeBehavior]]
    login_bonuses: Optional[List[LoginBonus]]
    beginner_login_bonuses: Optional[List[BeginnerLoginBonus]]
    beginner_login_bonus_summaries: Optional[List[BeginnerLoginBonusSummary]]
    limited_login_bonuses: Optional[List[LimitedLoginBonus]]
    login_bonus_live2ds: Optional[List[LoginBonusLive2d]]
    events: Optional[List[Event]]
    event_musics: Optional[List[EventMusic]]
    event_deck_bonuses: Optional[List[EventDeckBonus]]
    event_rarity_bonus_rates: Optional[List[EventRarityBonusRate]]
    event_items: Optional[List[EventItem]]
    event_stories: Optional[List[EventStory]]
    event_exchange_summaries: Optional[List[EventExchangeSummary]]
    event_story_units: Optional[List[EventStoryUnit]]
    event_cards: Optional[List[EventCard]]
    preliminary_tournaments: Optional[List[PreliminaryTournament]]
    cheerful_carnival_summaries: Optional[List[CheerfulCarnivalSummary]]
    cheerful_carnival_teams: Optional[List[CheerfulCarnivalTeam]]
    cheerful_carnival_party_names: Optional[List[CheerfulCarnivalPartyName]]
    cheerful_carnival_character_party_names: Optional[
        List[CheerfulCarnivalCharacterPartyName]
    ]
    cheerful_carnival_live_team_point_bonuses: Optional[
        List[CheerfulCarnivalLiveTeamPointBonus]
    ]
    cheerful_carnival_rewards: Optional[List[CheerfulCarnivalReward]]
    cheerful_carnival_result_rewards: Optional[List[CheerfulCarnivalResultReward]]
    appeals: Optional[List[Appeal]]
    boosts: Optional[List[Boost]]
    boost_presents: Optional[List[BoostPresent]]
    boost_present_costs: Optional[List[BoostPresentCost]]
    episode_characters: Optional[List[EpisodeCharacter]]
    custom_profile_text_colors: Optional[List[CustomProfileTextColor]]
    custom_profile_text_fonts: Optional[List[CustomProfileTextFont]]
    custom_profile_player_info_resources: Optional[List[CustomProfilePlayerInfoResource]]
    custom_profile_general_background_resources: Optional[
        List[CustomProfileGeneralBackgroundResource]
    ]
    custom_profile_story_background_resources: Optional[
        List[CustomProfileStoryBackgroundResource]
    ]
    custom_profile_collection_resources: Optional[List[CustomProfileCollectionResource]]
    custom_profile_member_standing_picture_resources: Optional[
        List[CustomProfileMemberStandingPictureResource]
    ]
    custom_profile_shape_resources: Optional[List[CustomProfileShapeResource]]
    custom_profile_etc_resources: Optional[List[CustomProfileEtcResource]]
    custom_profile_member_resource_exclude_cards: Optional[List[Union[dict, str, int]]]
    custom_profile_gachas: Optional[List[CustomProfileGacha]]
    custom_profile_gacha_tabs: Optional[List[Union[dict, str, int]]]
    streaming_live_bgms: Optional[List[StreamingLiveBgm]]
    omikujis: Optional[List[Omikuji]]
    omikuji_groups: Optional[List[OmikujiGroup]]
    omikuji_rates: Optional[List[OmikujiRate]]
    omikuji_costs: Optional[List[OmikujiCost]]
    omikuji_rewards: Optional[List[OmikujiReward]]
    virtual_booth_shops: Optional[List[VirtualBoothShop]]
    special_seasons: Optional[List[SpecialSeason]]
    special_season_areas: Optional[List[SpecialSeasonArea]]
    rank_match_penalties: Optional[List[RankMatchPenalty]]
    rank_match_placements: Optional[List[RankMatchPlacement]]
    rank_match_bonus_point_conditions: Optional[List[RankMatchBonusPointCondition]]
    rank_match_seasons: Optional[List[RankMatchSeason]]
    rank_match_tiers: Optional[List[RankMatchTier]]
    rank_match_tier_bonus_points: Optional[List[RankMatchTierBonusPoint]]
    rank_match_grades: Optional[List[RankMatchGrade]]
    rank_match_classes: Optional[List[RankMatchClass]]
    limited_title_screens: Optional[List[LimitedTitleScreen]]
    panel_mission_campaigns: Optional[List[Union[dict, str, int]]]